### ISSUE TITLE
Speed Up FuzzyMatch

### ISSUE THREAD

**Issue by byvlstr** [kicktipp/jlot#8]
Create a FuzzyMatch toggle in the user profile, so that you can disable the FuzzyMatch, e.g. for a certain period.
Depending on the pushed texts, disabling could be useful as it should speed up JLot and keep the translator in the flow.

**Comment by kicktipp** [comment]
A toggle is useless as most users forget to activate it again so they don't use fuzzy Matches at all. It would be much better to speed up the fuzzy match. For long text this might not be easy, but the plans are to split large text into chunks anyway.

**Comment by byvlstr** [comment]
Then let's do a timed Toggle, 24 hours. Also, it is not a problem with large texts. The Fuzzy match also takes time for short tokens, but because of reasons and some situations, it takes longer.

**Comment by kicktipp** [comment]
fixed. The process is now much faster. The problem was too many threads doing the same thing at the same time (FuzzyMatchUpdater)
